# Generated by Django 3.1.3 on 2020-11-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.IntegerField(max_length=200, unique=True)),
                ('level', models.CharField(choices=[('fskm', 'FSKM'), ('fpa', 'FPA')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('IC_no', models.IntegerField(max_length=20)),
                ('matric_no', models.IntegerField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=200)),
                ('scholarship', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=200)),
                ('family_income', models.IntegerField(max_length=30)),
                ('family_dependent', models.IntegerField(max_length=30)),
                ('health', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('family_problems', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
            ],
        ),
    ]
